#!/command/with-contenv bash
# shellcheck source-path=source-stubs
# shellcheck source-path=SCRIPTDIR

source /scripts/common

"${s6wrap[@]}" echo "Container version: $(</.CONTAINER_VERSION)"
"${s6wrap[@]}" echo ""
"${s6wrap[@]}" echo "Hardware information:"
"${s6wrap[@]}" echo "Machine:   $(uname -m)"
"${s6wrap[@]}" echo "Processor: $(uname -p)"
"${s6wrap[@]}" echo "Platform:  $(uname -i)"
