#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091,SC2068
source /scripts/common

# don't start if the signup-uat.sh script is running
#while [[ -f /run/.pause-fr24feed ]]; do
#  sleep 1
#done

# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then
  # fr24feed can be run natively
  # shellcheck disable=SC2068,SC2154
  ${s6wrap[@]} echo "starting /usr/local/bin/fr24feed natively"
  ${s6wrap[@]} /usr/local/bin/fr24feed --version
  ${s6wrap[@]} /usr/local/bin/fr24feed | stdbuf -oL grep -v '[feed]'
else
  # fr24feed needs qemu
  # shellcheck disable=SC2068
  ${s6wrap[@]} echo "starting /usr/local/bin/fr24feed in qemu"
  ${s6wrap[@]} qemu-arm-static /usr/local/bin/fr24feed --version
  ${s6wrap[@]} qemu-arm-static /usr/local/bin/fr24feed | stdbuf -oL grep -v '[feed]'
fi
