#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091,SC2068
source /scripts/common

# don't start if the signup-uat.sh script is running
#while [[ -f /run/.pause-fr24feed ]]; do
#  sleep 1
#done

FR24_CMD=()

# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then
  # fr24feed can be run natively
  NATIVE="natively"
else
  # fr24feed needs qemu
  FR24_CMD+=("qemu-arm-static")
  NATIVE="using qemu"
fi

FR24_CMD+=("/usr/local/bin/fr24feed")

FILTER_TERMS=("-e" "[feed][i]sent" "-e" "[feed][n]syncing")

if chk_enabled "$VERBOSE_LOGGING"; then
  VERBOSE_REMARK="in Verbose Logging mode"
else
  FILTER_TERMS+=("-e" "[mlat]")
  VERBOSE_REMARK="in non-verbose Logging mode"
fi

"${s6wrap[@]}" echo "Starting fr24feed (adsb) $NATIVE $VERBOSE_REMARK"
"${s6wrap[@]}" "${FR24_CMD[@]}" | stdbuf -oL grep -v -F "${FILTER_TERMS[@]}"
