#!/command/with-contenv bash
#shellcheck shell=bash

# sleep forever if UAT is not available
if [[ -z "$FR24KEY_UAT" ]]; then
  sleep infinity
fi

# don't start if the signup-uat.sh script is running
while [[ -f /run/.pause-fr24feed ]]; do
  sleep 1
done

# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then
  # fr24feed can be run natively
  /usr/local/bin/fr24feed --monitor-file=/dev/shm/uat-decoder.txt --http-listen-port=8755 --config-file=/etc/fr24uat-feed.ini --unit=fr24uat-feed | stdbuf -oL grep -v '[feed]'
else
  # fr24feed needs qemu
  qemu-arm-static /usr/local/bin/fr24feed --monitor-file=/dev/shm/uat-decoder.txt --http-listen-port=8755 --config-file=/etc/fr24uat-feed.ini --unit=fr24uat-feed | stdbuf -oL grep -v '[feed]'
fi
