#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091,SC2068
source /scripts/common

# don't start if the signup-uat.sh script is running
#while [[ -f /run/.pause-fr24feed ]]; do
#  sleep 1
#done

# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then
  # fr24feed can be run natively
  # shellcheck disable=SC2068,SC2154
  if chk_enabled "$VERBOSE_LOGGING"; then
    ${s6wrap[@]} echo "Starting fr24feed (adsb) natively in Verbose Logging mode"
    ${s6wrap[@]} /usr/local/bin/fr24feed | stdbuf -oL grep -v '\[feed\]'
  else
    ${s6wrap[@]} echo "Starting fr24feed (adsb) natively in Non-verbose Logging mode. Only [stats] items will be shown"
    ${s6wrap[@]} /usr/local/bin/fr24feed | stdbuf -oL grep -v '\[feed\]' | grep '\[stats\]'
  fi
else
  # fr24feed needs qemu
  # shellcheck disable=SC2068
  if chk_enabled "$VERBOSE_LOGGING"; then
    ${s6wrap[@]} echo "Starting fr24feed (adsb) in qemu with Verbose Logging mode"
    ${s6wrap[@]} qemu-arm-static /usr/local/bin/fr24feed | stdbuf -oL grep -v '\[feed\]'
  else
    ${s6wrap[@]} echo "Starting fr24feed (adsb) in qemu with Non-verbose Logging mode. Only [stats] items will be shown"
    ${s6wrap[@]} qemu-arm-static /usr/local/bin/fr24feed | stdbuf -oL grep -v '\[feed\]' | grep '\[stats\]'
  fi
fi
