#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154

# shellcheck disable=SC1091
source /scripts/common

# sleep forever if UAT is not available
if [[ -z "$FR24KEY_UAT" ]]; then
  sleep infinity
fi

# fr24feed regularly uses fcntl on all available fds, causing CPU / syscall load
# limit fr24feed to 128 open file descriptors to work around this issue
ulimit -n 128

# don't start if the signup-uat.sh script is running
#while [[ -f /run/.pause-fr24feed ]]; do
#  sleep 1
#done

# wait a while so the adsb feeder instance is running
sleep 15


FR24_CMD=()

# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then
  # fr24feed can be run natively
  NATIVE_REMARK="natively"
else
  # fr24feed needs qemu
  FR24_CMD+=("qemu-arm-static")
  NATIVE_REMARK="using qemu"
fi

FR24_CMD+=("/usr/local/bin/fr24feed")
FR24_CMD+=("--monitor-file=/dev/shm/uat-decoder.txt" "--http-listen-port=8755" "--config-file=/etc/fr24uat-feed.ini" "--unit=fr24uat-feed")

FILTER_TERMS=("-e" "[feed][i]sent" "-e" "[feed][n]syncing")

if chk_enabled "$VERBOSE_LOGGING"; then
  VERBOSE_REMARK="in Verbose Logging mode"
else
  FILTER_TERMS+=("-e" "[mlat]")
  VERBOSE_REMARK="in non-verbose Logging mode"
fi

"${s6wrap[@]}" echo "Starting fr24feed (adsb) $NATIVE_REMARK $VERBOSE_REMARK"
"${s6wrap[@]}" "${FR24_CMD[@]}" | stdbuf -oL grep -v -F "${FILTER_TERMS[@]}"
