#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -o pipefail

if [ "$VERBOSE_LOGGING" = "true" ]; then
  # show everything
  tail -F /var/log/fr24feed.log
else
  # filter out noisy info, notice & warning messages
  tail -F /var/log/fr24feed.log | awk -W Interactive '! /\[[a-zA-Z]+\]\[(i|n|w)\]/'
fi
