#!/usr/bin/with-contenv sh
#shellcheck shell=sh

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${BEASTHOST}" ]; then
  echo "ERROR: BEASTHOST environment variable not set"
  EXITCODE=1
fi
if [ -z "${FR24KEY}" ]; then
  echo "ERROR: FR24KEY environment variable not set"
  EXITCODE=1
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
fi

# Set up fr24feed
{
  echo receiver="beast-tcp"
  echo fr24key="${FR24KEY}"
  echo host="${BEASTHOST}:${BEASTPORT}"
  echo bs="yes"
  echo raw="yes"
  echo logmode="1"
  echo logpath="/var/log"
  echo mlat="${MLAT}"
  echo mlat-without-gps="${MLAT}"
  echo bind-interface="0.0.0.0"
} > /etc/fr24feed.ini
