#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2153

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${BEASTHOST}" ]; then
  echo "ERROR: BEASTHOST environment variable not set"
  EXITCODE=1
fi
if [ -z "${FR24KEY}" ]; then
  echo "ERROR: FR24KEY environment variable not set"
  EXITCODE=1
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
fi

# Set up fr24feed
{
  echo receiver="beast-tcp"
  echo fr24key="${FR24KEY}"
  echo host="${BEASTHOST}:${BEASTPORT}"
  echo bs="no"
  echo raw="no"
  echo logmode="1"
  echo logpath="/var/log"
  echo mlat="no"
  echo mlat-without-gps="no"
  if [ -n "${BIND_INTERFACE}" ]; then
    echo bind-interface="${BIND_INTERFACE}"
  fi
} > /etc/fr24feed.ini

# prepare directories (from /usr/lib/fr24/create_missing_directories.sh)
mkdir -p /run/fr24feed

# prepare status file (from /usr/lib/fr24/create_missing_directories.sh)
touch /dev/shm/decoder.txt

# Print fr24 version.
# Test fr24feed can run natively (without qemu)
if /usr/local/bin/fr24feed --version > /dev/null 2>&1; then 
  # fr24feed can be run natively
  echo "fr24feed version: $(/usr/local/bin/fr24feed --version)"
else
  # fr24feed needs qemu
  echo "fr24feed version: $(qemu-arm-static /usr/local/bin/fr24feed --version)"
fi

# prepare log file
rm /var/log/fr24feed.log > /dev/null 2>&1
touch /var/log/fr24feed.log
